Fix failing install of PyMuPDF in Docker
This has been failing since 1.19.1 and seems to have started working
again since 1.19.5, so we may as well upgrade to the latest version.

        fitz/fitz_wrap.c:2755:10: fatal error: fitz.h: No such file or directory

It's unclear from the changelog [^1] why it broke and why the install
is now working. It's unclear if this is related to building the image
on top of Mac M1 - while online discussions corroborate the problem
[^2], the versions that work for us are different e.g. 1.19.4 breaks.

We use the "fitz" module from PyMuPDF in several critcal parts of the
code, including address extraction / redaction and colour detection.
We should therefore deploy this upgrade with caution.

[^1]: https://github.com/pymupdf/PyMuPDF/blob/master/changes.txt
[^2]: https://github.com/pymupdf/PyMuPDF/discussions/1563#discussioncomment-2317416