Downgrade log for expected PDF exception
I've added a test to cover this. We do get other exceptions, one of
which I've included in the test:

    File "/home/vcap/app/app/precompiled.py", line 476, in _overlay_printable_areas_with_white
        page.mergePage(new_pdf.getPage(0))
      File "/usr/local/lib/python3.9/site-packages/PyPDF2/pdf.py", line 2239, in mergePage
        self._mergePage(page2)
      File "/usr/local/lib/python3.9/site-packages/PyPDF2/pdf.py", line 2248, in _mergePage
        originalResources = self["/Resources"].getObject()
      File "/usr/local/lib/python3.9/site-packages/PyPDF2/generic.py", line 516, in __getitem__
        return dict.__getitem__(self, key).getObject()
    KeyError: '/Resources'

While it's tempting to ignore these as well, it's unclear if they
represent an issue with the PDF or with the library. I've only seen
it happen once, so it doesn't seem worth the time to investigate at
the moment - the user still got a meaningful error.